export const STABLECOIN_PEG_GUARDIAN_HOOK_ABI = [
  // ── Read Functions ──────────────────────────────────────────────────
  {
    type: "function",
    name: "currentPrice",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pegPrice",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getDeviationBps",
    inputs: [],
    outputs: [{ name: "deviationBps", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "rebalanceCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "paused",
    inputs: [],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pendingOwner",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "authorizedCallback",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "chainlinkOracle",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "oracleStalenessThreshold",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "oracleDecimals",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "PRICE_PRECISION",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MAX_FEE",
    inputs: [],
    outputs: [{ name: "", type: "uint24" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "LARGECAP_SURCHARGE",
    inputs: [],
    outputs: [{ name: "", type: "uint24" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "CRITICAL_DEVIATION_BPS",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MAX_DEVIATION_BPS",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },

  // ── Write Functions ─────────────────────────────────────────────────
  {
    type: "function",
    name: "updatePrice",
    inputs: [{ name: "newPrice", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setPegPrice",
    inputs: [{ name: "newPeg", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "pause",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "unpause",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "acceptOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setAuthorizedCallback",
    inputs: [{ name: "_callback", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setChainlinkOracle",
    inputs: [
      { name: "_oracle", type: "address" },
      { name: "_stalenessThreshold", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updatePriceFromOracle",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updatePriceFromCallback",
    inputs: [{ name: "newPrice", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },

  // ── Events ──────────────────────────────────────────────────────────
  {
    type: "event",
    name: "SwapExecuted",
    inputs: [
      { name: "poolId", type: "bytes32", indexed: true },
      { name: "sender", type: "address", indexed: true },
      { name: "fee", type: "uint24", indexed: false },
      { name: "deviationBps", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "RebalanceNeeded",
    inputs: [
      { name: "poolId", type: "bytes32", indexed: true },
      { name: "deviationBps", type: "uint256", indexed: false },
      { name: "currentPrice", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "PriceUpdated",
    inputs: [
      { name: "oldPrice", type: "uint256", indexed: false },
      { name: "newPrice", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "PegPriceUpdated",
    inputs: [
      { name: "oldPeg", type: "uint256", indexed: false },
      { name: "newPeg", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "CallbackPriceUpdated",
    inputs: [
      { name: "oldPrice", type: "uint256", indexed: false },
      { name: "newPrice", type: "uint256", indexed: false },
      { name: "caller", type: "address", indexed: false },
    ],
  },
  {
    type: "event",
    name: "OraclePriceUpdated",
    inputs: [
      { name: "oldPrice", type: "uint256", indexed: false },
      { name: "newPrice", type: "uint256", indexed: false },
      { name: "roundId", type: "uint80", indexed: false },
    ],
  },
  {
    type: "event",
    name: "Paused",
    inputs: [{ name: "account", type: "address", indexed: false }],
  },
  {
    type: "event",
    name: "Unpaused",
    inputs: [{ name: "account", type: "address", indexed: false }],
  },
  {
    type: "event",
    name: "LiquidityAdded",
    inputs: [
      { name: "poolId", type: "bytes32", indexed: true },
      { name: "sender", type: "address", indexed: true },
    ],
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      { name: "previousOwner", type: "address", indexed: true },
      { name: "newOwner", type: "address", indexed: true },
    ],
  },
  {
    type: "event",
    name: "OwnershipTransferStarted",
    inputs: [{ name: "pendingOwner", type: "address", indexed: true }],
  },

  // ── Errors ──────────────────────────────────────────────────────────
  { type: "error", name: "NotOwner", inputs: [] },
  { type: "error", name: "NotPendingOwner", inputs: [] },
  { type: "error", name: "HookPaused", inputs: [] },
  { type: "error", name: "ZeroAddress", inputs: [] },
  { type: "error", name: "InvalidPrice", inputs: [] },
  { type: "error", name: "NotAuthorizedCallback", inputs: [] },
  { type: "error", name: "StaleOracleData", inputs: [] },
  { type: "error", name: "InvalidOraclePrice", inputs: [] },
  { type: "error", name: "OracleNotSet", inputs: [] },
] as const;
